---
- name: "My GNU/Debian Setup"
  hosts: localhost
  connection: local 

  tasks:
    - include_vars: vars/vars.yml
    - import_tasks: tasks/apt_base_pkgs.yml

    - include_role:
        name: Xorg

    - include_role:
        name: Qtile

    - include_role:
        name: AppImage

    - include_role:
        name: Floorp

    - include_role:
        name: Nix

    - import_tasks: tasks/nf_fonts.yml
    - import_tasks: tasks/kitty_terminal.yml
    - import_tasks: tasks/blesh.yml
    - import_tasks: tasks/batcat.yml

    - import_tasks: tasks/yadm.yml
