---
- name: "install base pkgs"
  become: true
  apt:
    pkg:
    - xserver-xorg
    - xinit
    - x11-xserver-utils
    - xdg-user-dirs

- name: "install related pkgs"
  become: true
  apt:
    pkg: "{{ xorg_additional_pkgs }}"

- name: "create User Dirs"
  ansible.builtin.command: "xdg-user-dirs-update"
