---
- name: "GetNF Install"
  ansible.builtin.shell: "curl -fsSL https://raw.githubusercontent.com/getnf/getnf/main/install.sh | bash"

- name: "Install JetBrains, Ubuntu Nerd Fonts"
  ansible.builtin.command: '{{ ansible_env.HOME }}/.local/bin/getnf -i "UbuntuMono JetBrainsMono"'
  args:
    chdir: "{{ ansible_env.HOME }}"

