---
- name: "Install X.org"
  become: true
  apt:
    pkg:
    - xserver-xorg
    - xinit
    - x11-xserver-utils
    - xdg-user-dirs

- name: "Install Qtile Required lib"
  become: true
  apt:
    pkg:
    - libpangocairo-1.0-0

- name: "Install Qtile Required python pkgs"
  become: true
  apt:
    pkg:
    - python3-pip
    - python3-xcffib
    - python3-cairocffi

- name: "Pip install Qtile"
  become: false
  ansible.builtin.shell: "pip install qtile --break-system-packages"

- name: "Create .xinitrc"
  copy:
    dest: "{{ ansible_env.HOME }}/.xinitrc"
    content: |
      exec qtile start

- name: "Install a list of Qtile related pkgs"
  become: true
  apt:
    pkg:
    - feh
    - sxhkd
    - rofi
    # - kitty
    # - dmenu

- name: "Create User Dirs"
  ansible.builtin.command: "xdg-user-dirs-update"
  args:
    chdir: "{{ ansible_env.HOME }}"
  # become: false
  # ansible.builtin.shell: "xdg-user-dirs-update"
