---
- name: "Install (yadm, git) packages"
  become: true
  apt:
    update_cache: true
    pkg:
    - git
    - yadm

- name: "yadm clone repo"
  ansible.builtin.command: "yadm clone --depth=1 {{ dotfiles_repo }}"
 
- name: "yadm checkout"
  ansible.builtin.command: 'yadm checkout "$HOME"'
 
